import Footer from "@/component/Footer";
import Navbar from "@/component/Navbar";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "../globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

const satoshi = localFont({
  src: [
    {
      path: "../../public/Satoshi-Regular.otf",
      weight: "400",
    },
    {
      path: "../../public/Satoshi-Medium.otf",
      weight: "500",
    },
  ],
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${satoshi.variable} h-full antialiased`}
    >
      <body className="font-satoshi">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
